server:
  port: 8085

spring:
  application:
    name: search-service
  data:
    elasticsearch:
      uris: http://localhost:9200
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
